bars:
  status_bar:
    screens:
      ['eDP-1']:
        position: top
        height: 30
tooltip:
  offset: 10
  blur_effect:
    enabled: true
    rounded_corners: true
    rounded_corners_type: 5
