debug: true
bars:
  primary_bar:
    enabled: true
    screens:
      - '*'
    class_name: "yasb_bar"
    alignment:
      position: "top"
      align: "center"
    window_flags:
      windows_app_bar: true
      hide_on_fullscreen: false
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 2
      bottom: 2
      left: 4
      right: 4
    blur_effect:
      enabled: true
      dark_mode: true
    widgets:
      left:
        - komorebi_workspaces
        - active_window
      center:
        - clock
      right:
        - media
        - microphone
        - volume
        - wifi
        - battery
        - notifications
widgets:
  komorebi_workspaces:
    type: komorebi.workspaces.WorkspaceWidget
    options:
      label_workspace_btn: '{name}'
      label_workspace_active_btn: '{name}'
      label_workspace_populated_btn: '{name}'
      label_default_name: '{index}'
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
  active_window:
    type: yasb.active_window.ActiveWindowWidget
    options:
      label: '{win[title]}'
      label_alt: '[class_name=''{win[class_name]}'' exe=''{win[process][name]}'' hwnd={win[hwnd]}]'
      label_no_window: ''
      label_icon: true
      label_icon_size: 16
      max_length: 32
      max_length_ellipsis: '...'
      monitor_exclusive: false
  clock:
    type: yasb.clock.ClockWidget
    options:
      label: '{%a, %d %b %I:%M %p}'
  microphone:
    type: yasb.microphone.MicrophoneWidget
    options:
      label: '{icon}'
      label_alt: '{icon}'
  volume:
    type: yasb.volume.VolumeWidget
    options:
      label: '{icon}'
      label_alt: '{icon}'
  wifi:
    type: yasb.wifi.WifiWidget
    options:
      label: '{wifi_icon}'
      label_alt: '{wifi_icon}'
      ethernet_label: '{wifi_icon}'
      ethernet_label_alt: '{wifi_icon}'
  battery:
    type: yasb.battery.BatteryWidget
    options:
      label: '{icon}'
      label_alt: '{icon}'
      status_icons:
        icon_charging: ''
        icon_critical: '󰂎'
        icon_low: '󰁼'
        icon_medium: '󰁾'
        icon_high: '󰂀'
        icon_full: '󰁹'
  notifications:
    type: yasb.notifications.NotificationsWidget
    options:
      label: ""
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: toggle_notification
        on_right: do_nothing
        on_middle: do_nothing
  media:
    type: yasb.media.MediaWidget
    options:
      label: '{title}{s}{artist}'
      label_alt: '{title}'
      separator: ' - '
      hide_empty: true
      callbacks:
        on_left: toggle_media_menu
        on_middle: do_nothing
        on_right: do_nothing
      max_field_size:
        label: 20
        label_alt: 20
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 100
      thumbnail_padding: 10
      thumbnail_edge_fade: true
      icons:
        prev_track: "\uE892"
        next_track: "\uE893"
        play: "\uE768"
        pause: "\uE769"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: normal
        border_color: system
        alignment: center
        direction: down
        thumbnail_corner_radius: 8
        thumbnail_size: 0
        max_title_size: 60
        max_artist_size: 20
        show_volume_slider: true
      scrolling_label:
        enabled: true
        style: bounce
        update_interval_ms: 40